POST http://localhost:3333/hosts/create
Content-Type: application/json

{
  "name": "Servidor De Teste",
  "host": "www.google.com",
  "alert_email": "lausiowatela@gmail.com",
  "monitors": [
    {
      "type": "PING",
      "config": {
        "host": "servidor.empresa.com",
        "timeout": 5000,
        "retries": 3,
        "packetSize": 64
      },
      "interval": 60
    },
  
    {
      "type": "SNMP",
      "config": {
        "host": "servidor.empresa.com",
        "port": 161,
        "community": "public",
        "version": "2c",
        "oids": [
          "1.3.6.1.2.1.1.3.0",
          "1.3.6.1.2.1.25.1.1.0"
        ],
        "timeout": 5000
      },
      "interval": 120
    },
    {
      "type": "WEBHOOK",
      "config": {
        "url": "https://infrawatch.site/unique-id-123",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        },
        "payload": {
          "source": "monitoring-system",
          "timestamp": "1232",
          "system": "servidor.empresa.com"
        },
        "timeout": 8000
      },
      "interval": 300
    }
  ],
  "slaConfig": {
    "uptimeTarget": 99.95,
    "maxDowntime": 360,
    "responseTimeTarget": 500,
    "monitoringWindow": "monthly"
  }
}